name := "Regresion Lineal Apache Spark"
version := "1.0"
scalaVersion := "2.12.15"
libraryDependencies += "org.apache.spark" %% "spark-core" % "3.2.1"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "3.3.0"
libraryDependencies += "org.apache.spark" %% "spark-ml" % "2.2.1"
libraryDependencies += "org.apache.spark" %% "spark-mllib" % "2.0.1"
